[package]
name = "cli"
version.workspace = true
edition = "2024"
publish = false
license.workspace = true

[[bin]]
name = "dfs"
path = "src/main.rs"

[dependencies]
cdc = { version = "0.0.1", path = "../cdc" }
clap = { version = "4.6.6", features = ["derive"] }
db = { version = "0.0.1", path = "../db" }
mountfs = { path = "../mountfs" }
store = { version = "0.0.1", path = "../store" }

[dev-dependencies]
tempfile = "3.27.0"
