#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11.0.* only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi



echo
echo This utility will restore a previous state of the DedupFS database.
echo This will overwrite the current database state.  If you do not want
echo that, simply close the console window where this utility is running.
echo
echo Press <enter> to continue...
pause
echo

### Parameters ###
# repo=<repository directory>     | default: '..' (parent of working directory)
# from=<restore script file name> | default: none - for simple db file restore
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx512m -cp "$APPDIR/lib/*" dedup.dbRestore "$@"
ERRORLEVEL=$?
if [ $ERRORLEVEL -ne 0 ]; then
  echo Database restore finished with error code %ERRORLEVEL%, exiting...
  exit 1
else
  echo Database restore finished.
fi
