#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11.0.* only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi



### Mount options ###
# Log directory: -DLOG_BASE=<log base directory>
# Heap space   : -Xmx256M - mount needs at least 96MB RAM.
# 1. parameter : <repository directory>
# 2. parameter : <mount point>
# Additional optional parameters:
# -readOnly=true
# -noDbBackup=true
# -copyWhenMoving=true
# -temp=<temp dir>

### Note ###
# -Dfile.encoding=UTF-8 is necessary for FUSE operations.
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx512m -Dfile.encoding=UTF-8 -cp "$APPDIR/lib/*" dedup.mount "$@"
