#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11.0.* only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi



### Parameters ###
# repo=<repository directory> | default: working directory
# mount=<mount point>         | default: /mnt/dedupfs
# readOnly=true               | default: false
# noDbBackup=true             | default: false
# copyWhenMoving=true         | default: false
# gui=true                    | default: default: false, true in script - true to show server GUI
# temp=<temp dir>             | default: 'dedupfs-temp' in the user's temp dir
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx512m -Dfile.encoding=UTF-8 -cp "$APPDIR/lib/*" dedup.mount gui=true "$@"
