#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$($APPDIR/helpers/set-java java $APPDIR/jrex/bin/java) || exit 1


### Parameters ###
# repo=<repository directory>     | default: '..' (parent of working directory)
$JAVA "-DLOG_BASE=$APPDIR/log" -cp "$APPDIR/lib/*" dedup.reclaimSpace2 "$@"
