#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11.0.* only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi

# Init options:
# First parameter: <repository directory>
# Log directory: -DLOG_BASE=<log base directory>
$JAVA "-DLOG_BASE=$APPDIR/log" -cp "$APPDIR/lib/*" dedup.init "$@"
