#!/bin/bash
if [ -f "$2" ]; then JAVA="$2"; else JAVA="$1"; fi
JAVAVERSION=$("$JAVA" -fullversion 2>&1)
if [[ $JAVAVERSION == *"\"25"*"-LTS"* ]]; then
  echo "$JAVA"
else
  >&2 echo "This software has been tested with Java 25 only."
  >&2 echo "Detected Java version: $JAVAVERSION"
  exit 1
fi
