[package]
name = "cli"
version = "0.1.0"
edition = "2024"
publish = false

[[bin]]
name = "backup"
path = "src/main.rs"

[dependencies]
blake3 = "1.8.5"
cdc = { version = "0.1.0", path = "../cdc" }
clap = { version = "4", features = ["derive"] }
db = { version = "0.1.0", path = "../db" }
rayon = "1.12.0"
walkdir = "2.5.0"
