#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1


### Parameters ###
# repo=<repository directory>                                     | default: .. (parent of working directory)
# dbBackup=false                                                  | default: true
# blacklistDir=<name of directory in repo with files to blacklist>| default: blacklist
# deleteFiles=<delete files in blacklistDir when blacklisted?>    | default: true
# dfsBlacklist=<name of blacklist directory in dedup file system> | default: blacklist
# deleteCopies=<delete all copies of blacklisted files?>          | default: false
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx128m -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.blacklist "$@"
ERRORLEVEL=$?
if [ $ERRORLEVEL -ne 0 ]; then
  echo "Blacklisting finished with error code $ERRORLEVEL, exiting..."
  exit $ERRORLEVEL
else
  echo "Blacklisting finished successfully."
fi
