#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$($APPDIR/helpers/set-java java $APPDIR/jrex/bin/java) || exit 1


### Parameters ###
# repo=<repository directory>                                     | default: '..' (parent of working directory)
# blacklistDir=<name of directory in repo with files to blacklist>| default: 'blacklist'
# deleteFiles=<delete files in blacklistDir when blacklisted?>    | default: 'false'
# dfsBlacklist=<name of blacklist directory in dedup file system> | default: 'blacklist'
# deleteCopies=<delete all copies of blacklisted files?>          | default: 'false'
$JAVA "-DLOG_BASE=$APPDIR/log" -cp "$APPDIR/lib/*" dedup.blacklist "$@"
