#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11 only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi

# Options for dbrestore:
# from=<script file>              | default: none (direct file restore)
# repo=<repository directory>     | default: working directory
# -DLOG_BASE=<log base directory> | mandatory for sensible logging
$JAVA "-DLOG_BASE=$APPDIR/" -cp "$APPDIR/lib/*" dedup.Main dbrestore "$@"
ERRORLEVEL=$?
if [ $ERRORLEVEL -ne 0 ]; then
  echo Database restore finished with error code %ERRORLEVEL%, exiting...
  exit 1
else
  echo Database restore finished.
fi
