#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1


echo
echo "This utility will restore a previous state of the DedupFS database."
echo "This will overwrite the current database state.  If you do not want"
echo "that, simply close the console window where this utility is running."
echo
read -n 1 -r -s -p "Press any key to continue..."
echo

### Parameters ###
# repo=<repository directory>     | default: '..' (parent of working directory)
# from=<restore script file name> | default: none - for simple db file restore
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx512m -cp "$APPDIR/lib/*" dedup.dbRestore "$@"
ERRORLEVEL=$?
if [ $ERRORLEVEL -ne 0 ]; then
  echo "Database restore finished with error code $ERRORLEVEL, exiting..."
  exit 1
else
  echo "Database restore finished."
fi
