#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1


### Parameters ###
# repo=<repository directory> | default: .. (parent of working directory)
# mount=<mount point>         | default: /mnt/dedupfs - the 'mount=' prefix can be omitted
# readOnly=true               | default: false
# dbBackup=false              | default: true
# copyWhenMoving=true         | default: false
# gui=true                    | default: false - true to show server GUI
# temp=<temp dir>             | default: dedupfs-temp in the user's temp dir
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx512m -Dfile.encoding=UTF-8 -Dlogback.configurationFile=logback-server.xml -cp "$APPDIR/lib/*" dedup.mount "$@"
