#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1


### Parameters ###
# repo=<repository directory> | default: '..' (parent of working directory)
### Commands ###
# call 'fsc help' for more information
if [ "$1" = "find" ] || [ "$1" = "list" ] || [ "$1" = "stats" ]; then
  $JAVA "-DLOG_BASE=$APPDIR/log" -Xmx256m -Dlogback.configurationFile=logback-readonly.xml -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.fsc "$@"
else
  $JAVA "-DLOG_BASE=$APPDIR/log" -Xmx256m -cp "$APPDIR/lib/*:$APPDIR/lib-h2/*" dedup.fsc "$@"
fi
# No confirmation, no additional output, fsc is a plain command line tool.
