#!/bin/bash
APPDIR=$(dirname "$0")
if [ -d "$APPDIR"/jrex ]; then JAVA=$APPDIR/jrex/bin/java; else JAVA=java; fi
JAVAVERSION=$($JAVA -version 2>&1 | head -1)
if [[ $JAVAVERSION != *"\"11.0."* ]]; then
  echo "This software has been tested with Java 11 only."
  echo "Detected Java version: $JAVAVERSION"
  exit 1
fi
if ! $APPDIR/db-backup; then exit 1; fi

# Options for reclaim space 1:
# keepdays=<number of days to keep> | default: 0
# repo=<repository directory>       | default: working directory
# -DLOG_BASE=<log base directory>   | mandatory for sensible logging
$JAVA "-DLOG_BASE=$APPDIR/" -Dfile.encoding=UTF-8 -cp "$APPDIR/lib/*" dedup.Server reclaimspace1 "$@"

echo
echo "Note if you plan to run the reclaim-space-2 utility: That"
echo "utility will compact the DedupFS data store. Afterwards,"
echo "older database backups can not be fully applied anymore."
