#!/bin/bash
APPDIR=$(dirname "$0")
JAVA=$("$APPDIR/helpers/set-java" java "$APPDIR/jrex/bin/java") || exit 1


### Parameters ###
# repo=<repository directory>     | default: '..' (parent of working directory)
$JAVA "-DLOG_BASE=$APPDIR/log" -Xmx256m -cp "$APPDIR/lib/*" dedup.stats "$@"
if [ $ERRORLEVEL -ne 0 ]; then
  echo "Statistics finished with error code $ERRORLEVEL, exiting..."
  exit $ERRORLEVEL
else
  echo "Statistics finished successfully."
fi
